### ISSUE TITLE
Building: instalation path

### ISSUE THREAD

**Issue by sukamenev** [artyom-beilis/pytorch_dlprim#81]
I'm working in VE.

My path to python packages is:
/home/.../ve_root/lib/python3.11/site-packages

but `make install` only support path ends like "python/pytorch_ocl"

It's is non compatible with python Virtual Environment.

**Comment by artyom-beilis** [comment]
Idea you can add PYTHONPATH to this external package.

Anywhay now there are whl avalible.

**Comment by sukamenev** [comment]
Как лучше тестировать: бинарные релизы или компилировать?

**Comment by artyom-beilis** [comment]
> Как лучше тестировать: бинарные релизы или компилировать?

Basically binary is for ease of use especially on Windows where building anything is pain in b...m. 

So it is up to you. Binary releases is convenience - but I wouldn't build them for any new commit since it takes time - especially since I need to reboot to windows 

If you can built the project on your own (especially on Linux) than it is really trivial. More so you can install package and if you do your own updates just replace `pt_ocl.so` and `__init__.py` - it all this packages contains `:-)`

(Closing it - but feel free to reopen if any new questions appear)
